### PR TITLE
Make tabs renamable inline

### PR DESCRIPTION
**Pull request by eduard-sukharev**
Further improving QTabBar - make it renamable inline.
Solution took from my [question on SO](http://stackoverflow.com/questions/30269046/inline-renaming-of-a-tab-in-qtabbar-qtabwidget/30269356#30269356)

### CODE REVIEW

**Comment by eduard-sukharev** [comment]
I have no idea what name convention you use so i've tried to follow it as closely as i could understand from the rest of your code.

**Comment by LysanderGG** [comment]
Part of Hungarian notation, see the part about scope in the examples [here](http://en.wikipedia.org/wiki/Hungarian_notation#Examples).

EDIT: I saw after this message that you updated it, the names fit the convention, thanks!

**Comment by LysanderGG** [comment]
About the C++11 option, I don't find the line comment anymore, but I got a mail notification.
It is indeed needed for the "nullptr" keyword, thanks for spotting this!

**Comment by eduard-sukharev** [comment]
oh my gods, Hungarian notation is awful. I respect your choice in your project, but i strongly recommend you to consider switching to something better in your further projects. See [Disadvantages section](http://en.wikipedia.org/wiki/Hungarian_notation#Disadvantages) and `Notable opinions` which is right after it.

**Comment by LysanderGG** [comment]
I have already read these sections but I don't find the argumentd against that relevant.
I started to implement this for my work where we use HN so I did not consider changing for another notation when publishing it here.

**Comment by eduard-sukharev** [comment]
Ok, i've moved border values to be const static ints. Also removed mouseReleaseEvent call on doubleClickEvent. The c++11 is still there, in .pro file.

**Comment by LysanderGG** [comment]
I merged your pull request after having fixed the const static members (missing const qualifier).
I moved them back into the method since it was what I was originally thinking about.
I will add an option to enable or not this new functionality soon.

Thanks a lot for your contribution!
Please do not hesitate if you have new ones or if you have ideas for improvements (I will think about changing the naming convention).

**Comment by eduard-sukharev** [comment]
thanks for fixing - last changes were made on machine with 14.04 distro with 4.8 Qt, which requires a lot of changes to build the project, so it was almost blind guess.

Also, there's no way to "cancel" tab name edit now - it does not react to Esc key or focus loosing.

**Pull request merged**
